basic_app/urls.py
from django.conf.urls import url
from . import views

# TEMPLATE URLS
app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

learning_users_me/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name="special"),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)  # Adds on attributes to the User class (think of it as extending)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)  # profile_pics is in the media folder

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from django.shortcuts import render
from .forms import UserProfileInfoForm, UserForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return render(request, 'basic_app/special.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)    # Hashing the password
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user     # Sets up the one to one relationship from models

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context_dict = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
    }

    return render(request, 'basic_app/registration.html', context=context_dict)

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and FAILED")
            print("Username: {} and Password: {}".format(username, password))
            return HttpResponse("invalid login details supplied")

    else:
        return render(request, 'basic_app/login.html', {})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-static-top">
        <div class="container">
            <ul class="navbar-nav">
                <li class=""nav-item><a href="{url 'index'}" class="navbar-brand">Django</a></li>
                <li class=""nav-item><a href="{% url 'admin:index' %}" class="nav-link">Admin</a></li>
                <li class=""nav-item><a href="{% url 'basic_app:register' %}" class="nav-link">Register</a></li>

                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
                {% else %}
                <li><a href="{% url 'basic_app:user_login' %}" class="nav-link">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
    {% block body_block %}
        <div class="jumbotron">
            <h1>Django Level Five</h1>
        </div>
    {% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
    {% block body_block %}
        <div class="jumbotron">
            <h1>Please Login</h1>
            <form action="{% url 'basic_app:user_login' %}" method="post">
                {% csrf_token %}
                <label for="username">Username:</label>
                <input type="text" name="username" placeholder="Enter Username">

                <label for="password">Password:</label>
                <input type="password" name="password">

                <input type="submit" name="" value="Login">
            </form>
        </div>
    {% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the form:</h3>

        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
        {% endif %}
    </div>

{% endblock %}

templates/basic_app/special.html
{% extends 'basic_app/base.html' %}
    {% block body_block %}
        <div class="jumbotron">
            <h1>You have been recognized. Welcome to the Team.</h1>
        </div>
    {% endblock %}